# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/main/python/fearank/ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 554)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(10, 10, 581, 481))
        self.tabs.setObjectName("tabs")
        self.tab_config = QtWidgets.QWidget()
        self.tab_config.setAccessibleName("")
        self.tab_config.setObjectName("tab_config")
        self.file_group = QtWidgets.QGroupBox(self.tab_config)
        self.file_group.setGeometry(QtCore.QRect(10, 10, 561, 101))
        self.file_group.setObjectName("file_group")
        self.gridLayout = QtWidgets.QGridLayout(self.file_group)
        self.gridLayout.setObjectName("gridLayout")
        self.export_btn = QtWidgets.QPushButton(self.file_group)
        self.export_btn.setObjectName("export_btn")
        self.gridLayout.addWidget(self.export_btn, 1, 1, 1, 1)
        self.import_btn = QtWidgets.QPushButton(self.file_group)
        self.import_btn.setObjectName("import_btn")
        self.gridLayout.addWidget(self.import_btn, 0, 1, 1, 1)
        self.import_file = QtWidgets.QLineEdit(self.file_group)
        self.import_file.setReadOnly(True)
        self.import_file.setObjectName("import_file")
        self.gridLayout.addWidget(self.import_file, 0, 3, 1, 1)
        self.export_file = QtWidgets.QLineEdit(self.file_group)
        self.export_file.setObjectName("export_file")
        self.gridLayout.addWidget(self.export_file, 1, 3, 1, 1)
        self.config_group = QtWidgets.QGroupBox(self.tab_config)
        self.config_group.setGeometry(QtCore.QRect(10, 120, 561, 151))
        self.config_group.setObjectName("config_group")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.config_group)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.config_form_layout = QtWidgets.QFormLayout()
        self.config_form_layout.setObjectName("config_form_layout")
        self.csv_header_label = QtWidgets.QLabel(self.config_group)
        self.csv_header_label.setObjectName("csv_header_label")
        self.config_form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.csv_header_label)
        self.csv_header_checkbox = QtWidgets.QCheckBox(self.config_group)
        self.csv_header_checkbox.setText("")
        self.csv_header_checkbox.setChecked(True)
        self.csv_header_checkbox.setObjectName("csv_header_checkbox")
        self.config_form_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.csv_header_checkbox)
        self.gt_label = QtWidgets.QLabel(self.config_group)
        self.gt_label.setObjectName("gt_label")
        self.config_form_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.gt_label)
        self.gt_col = QtWidgets.QLineEdit(self.config_group)
        self.gt_col.setObjectName("gt_col")
        self.config_form_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gt_col)
        self.feature_col_label = QtWidgets.QLabel(self.config_group)
        self.feature_col_label.setObjectName("feature_col_label")
        self.config_form_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.feature_col_label)
        self.feature_cols = QtWidgets.QLineEdit(self.config_group)
        self.feature_cols.setObjectName("feature_cols")
        self.config_form_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.feature_cols)
        self.iterations_label = QtWidgets.QLabel(self.config_group)
        self.iterations_label.setObjectName("iterations_label")
        self.config_form_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.iterations_label)
        self.iterations = QtWidgets.QSpinBox(self.config_group)
        self.iterations.setAccelerated(True)
        self.iterations.setMinimum(1)
        self.iterations.setMaximum(100000)
        self.iterations.setObjectName("iterations")
        self.config_form_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.iterations)
        self.verticalLayout.addLayout(self.config_form_layout)
        self.method_selection_group = QtWidgets.QGroupBox(self.tab_config)
        self.method_selection_group.setGeometry(QtCore.QRect(10, 280, 561, 161))
        self.method_selection_group.setObjectName("method_selection_group")
        self.formLayoutWidget = QtWidgets.QWidget(self.method_selection_group)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 541, 121))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.f_score = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.f_score.setObjectName("f_score")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.f_score)
        self.mutual_info_regression = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.mutual_info_regression.setObjectName("mutual_info_regression")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mutual_info_regression)
        self.chi_square = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.chi_square.setObjectName("chi_square")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.chi_square)
        self.random_forest_classifier = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.random_forest_classifier.setObjectName("random_forest_classifier")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.random_forest_classifier)
        self.extra_trees_classifier = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.extra_trees_classifier.setObjectName("extra_trees_classifier")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.extra_trees_classifier)
        self.random_forest_regressor = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.random_forest_regressor.setObjectName("random_forest_regressor")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.random_forest_regressor)
        self.extra_trees_regressor = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.extra_trees_regressor.setObjectName("extra_trees_regressor")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.extra_trees_regressor)
        self.rmrmr_cpp = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.rmrmr_cpp.setChecked(False)
        self.rmrmr_cpp.setObjectName("rmrmr_cpp")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rmrmr_cpp)
        self.tabs.addTab(self.tab_config, "")
        self.tab_results = QtWidgets.QWidget()
        self.tab_results.setObjectName("tab_results")
        self.result_group = QtWidgets.QGroupBox(self.tab_results)
        self.result_group.setGeometry(QtCore.QRect(10, 10, 561, 431))
        self.result_group.setObjectName("result_group")
        self.ranking_results = QtWidgets.QTextEdit(self.result_group)
        self.ranking_results.setGeometry(QtCore.QRect(10, 30, 541, 391))
        self.ranking_results.setObjectName("ranking_results")
        self.clear_results_btn = QtWidgets.QToolButton(self.result_group)
        self.clear_results_btn.setGeometry(QtCore.QRect(500, 570, 51, 21))
        self.clear_results_btn.setObjectName("clear_results_btn")
        self.tabs.addTab(self.tab_results, "")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 500, 581, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progress_bar = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.horizontalLayout.addWidget(self.progress_bar)
        self.progress_info = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.progress_info.setText("")
        self.progress_info.setObjectName("progress_info")
        self.horizontalLayout.addWidget(self.progress_info)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.calculate_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.calculate_btn.setEnabled(False)
        self.calculate_btn.setObjectName("calculate_btn")
        self.horizontalLayout.addWidget(self.calculate_btn)
        self.close_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Feature Ranking"))
        self.file_group.setTitle(_translate("MainWindow", "Import / Export Data"))
        self.export_btn.setToolTip(_translate("MainWindow", "Export the ranking results as a text file"))
        self.export_btn.setText(_translate("MainWindow", "Export (.txt)"))
        self.import_btn.setToolTip(_translate("MainWindow", "Import a MSR & MET data .csv file"))
        self.import_btn.setText(_translate("MainWindow", "Import (.csv)"))
        self.import_file.setPlaceholderText(_translate("MainWindow", "data.csv"))
        self.export_file.setPlaceholderText(_translate("MainWindow", "Specify an output file name [optional]"))
        self.config_group.setTitle(_translate("MainWindow", "Configuration"))
        self.csv_header_label.setText(_translate("MainWindow", "Header First Row"))
        self.gt_label.setText(_translate("MainWindow", "Ground Truth Column"))
        self.gt_col.setText(_translate("MainWindow", "5"))
        self.feature_col_label.setText(_translate("MainWindow", "Feature Columns"))
        self.feature_cols.setToolTip(_translate("MainWindow", "Ranges like \"6-\", \"6-9\" or comma separated columns \"6,8,9\""))
        self.feature_cols.setText(_translate("MainWindow", "6-"))
        self.iterations_label.setWhatsThis(_translate("MainWindow", "Determines how many iterations the ranking method should run."))
        self.iterations_label.setText(_translate("MainWindow", "Iterations"))
        self.method_selection_group.setTitle(_translate("MainWindow", "Ranking Methods"))
        self.f_score.setText(_translate("MainWindow", "F-Score"))
        self.mutual_info_regression.setText(_translate("MainWindow", "Mutual Information Regression"))
        self.chi_square.setText(_translate("MainWindow", "Chi-Square"))
        self.random_forest_classifier.setText(_translate("MainWindow", "Random Forest Classifier"))
        self.extra_trees_classifier.setText(_translate("MainWindow", "Extra Trees Classifier"))
        self.random_forest_regressor.setText(_translate("MainWindow", "Random Forest Regressor"))
        self.extra_trees_regressor.setText(_translate("MainWindow", "Extra Trees Regressor"))
        self.rmrmr_cpp.setText(_translate("MainWindow", "rMRMR (C++ Implementation)"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_config), _translate("MainWindow", "Settings"))
        self.result_group.setTitle(_translate("MainWindow", "Ranking Results"))
        self.clear_results_btn.setText(_translate("MainWindow", "Clear"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_results), _translate("MainWindow", "Results"))
        self.calculate_btn.setText(_translate("MainWindow", "Calculate"))
        self.close_btn.setText(_translate("MainWindow", "Close"))

